### PR TITLE
adding Heebo font support for Hebrew language

### PR DESCRIPTION
**Pull request by arthurvaverko**

### CODE REVIEW

**Comment by chrisbevan** [comment]
Hi arthurvaverko, thanks for the PR. Unfortunately I cannot accept this work in its current form:

1. None of the font weights are included.
2. The skin is designed around the Roboto font. I do not wish to add additional font support.

Can you please tell me what language you wish to support / are not currently supported?

Thanks,
Chris.

**Comment by arthurvaverko** [comment]
Hebrew ...
it looks fine with Arial .. 
can you tell me what you mean when you say font weights are not included ?

**Comment by chrisbevan** [comment]
Ah - OK. The Heebo font would make a better fit I think. 

By font weight, I mean 'bold', light', 'black' etc. You've just replaced everything with regular Arial!

**Comment by arthurvaverko** [comment]
done, and done .. :)

**Pull request merged**
